export { default as SEO } from './seo'
export { default as GatsbyImage } from './gatsby-image'
export { default as Typograhy } from './typography'
export { default as WordSpinner } from './word-spinner'
export { default as Nav } from './nav'
